import puppeteer from 'puppeteer';
import { IAssessment } from '../models/Assessment';
import path from 'path';

export async function generateAssessmentPdf(assessment: IAssessment): Promise<Buffer> {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox'],
  });

  try {
    const page = await browser.newPage();

    const difficultyColor = (d: string) => {
      switch (d) {
        case 'easy': return '#16a34a';
        case 'medium': return '#ca8a04';
        case 'hard': return '#dc2626';
        default: return '#6b7280';
      }
    };

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    @page { margin: 20mm 25mm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Georgia', 'Times New Roman', serif; color: #1a1a2e; line-height: 1.6; padding: 20px; }
    .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #1a1a2e; padding-bottom: 15px; }
    .header h1 { font-size: 22px; margin-bottom: 5px; }
    .header .sub { font-size: 14px; color: #555; }
    .student-info { display: flex; justify-content: space-between; margin-bottom: 25px; gap: 20px; }
    .student-info .field { flex: 1; border-bottom: 1px solid #333; padding-bottom: 4px; font-size: 14px; }
    .student-info .field .label { font-weight: bold; font-size: 12px; color: #555; }
    .instructions { background: #f8fafc; padding: 12px 16px; border-radius: 6px; margin-bottom: 25px; font-size: 13px; border-left: 4px solid #6366f1; }
    .instructions strong { color: #1a1a2e; }
    .section { margin-bottom: 28px; page-break-inside: avoid; }
    .section h2 { font-size: 17px; color: #1a1a2e; border-bottom: 1px solid #ddd; padding-bottom: 6px; margin-bottom: 8px; }
    .section .instruction { font-size: 13px; color: #666; margin-bottom: 12px; font-style: italic; }
    .question { margin-bottom: 14px; padding-left: 8px; }
    .question .q-text { font-size: 14px; margin-bottom: 4px; }
    .question .q-meta { display: flex; gap: 8px; align-items: center; font-size: 12px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 11px; font-weight: 600; color: #fff; }
    .footer { text-align: center; font-size: 11px; color: #999; margin-top: 30px; border-top: 1px solid #ddd; padding-top: 10px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${assessment.title}</h1>
    <div class="sub">Time: ${assessment.metadata.timeEstimate || '3 Hours'} &nbsp;|&nbsp; Max Marks: ${assessment.metadata.totalMarks}</div>
  </div>

  <div class="student-info">
    <div class="field"><span class="label">Name</span><br>___________________________</div>
    <div class="field"><span class="label">Roll No.</span><br>___________________________</div>
    <div class="field"><span class="label">Section</span><br>___________________________</div>
  </div>

  <div class="instructions">
    <strong>General Instructions:</strong><br>${assessment.generalInstructions}
  </div>

  ${assessment.sections.map(section => `
  <div class="section">
    <h2>${section.name}: ${section.title}</h2>
    <div class="instruction">${section.instruction}</div>
    ${section.questions.map(q => `
    <div class="question">
      <div class="q-text"><strong>${q.number}.</strong> ${q.text}</div>
      <div class="q-meta">
        <span class="badge" style="background:${difficultyColor(q.difficulty)}">${q.difficulty.charAt(0).toUpperCase() + q.difficulty.slice(1)}</span>
        <span style="color:#6366f1;font-weight:600;">[${q.marks} Mark${q.marks > 1 ? 's' : ''}]</span>
      </div>
    </div>
    `).join('')}
  </div>
  `).join('')}

  <div class="footer">
    Page 1 of 1 &mdash; Generated by AI Assessment Creator
  </div>
</body>
</html>`;

    await page.setContent(html, { waitUntil: 'networkidle0' });
    const pdf = await page.pdf({
      format: 'A4',
      margin: { top: '20mm', bottom: '20mm', left: '25mm', right: '25mm' },
      printBackground: true,
    });

    return Buffer.from(pdf);
  } finally {
    await browser.close();
  }
}
